### ISSUE TITLE
Annotation on First line of New JSON Object , in Large Scale JSON files

### ISSUE THREAD

**Issue by Yumshot** [code-biscuits/json-biscuits#1]
![Screenshot from 2020-10-15 11-08-34](https://user-images.githubusercontent.com/46466387/96169596-3a12cc00-0ed7-11eb-93b8-1e678d43b2cb.png)
Opening and Closing Tag seems to work fine though
![Screenshot from 2020-10-15 11-12-11](https://user-images.githubusercontent.com/46466387/96169695-69c1d400-0ed7-11eb-8e91-52723b037739.png)
![Screenshot from 2020-10-15 11-12-18](https://user-images.githubusercontent.com/46466387/96169699-6a5a6a80-0ed7-11eb-855e-053d9b547616.png)

**Comment by CriticalMax** [comment]
Same Issue over here:
![issue](https://i.imgur.com/oItWtkB.png)

**Comment by Yumshot** [comment]
**Steps taken to diagnose so far** 

- Disabled JS/TS Biscuits 
- Reloaded VSC completely
- Down-Versioned and then Updated JSON biscuits once again.
- Tested with Two seperate large JSON Files of 5.6k Lines
[Test JSON 1](https://raw.githubusercontent.com/GHMatti/FiveM-JsonInfo/master/ghmatti_vehicle_data.json)   <- this is the bugged json : object within an array of objects
[Test JSON 2](https://raw.githubusercontent.com/GHMatti/FiveM-JsonInfo/master/ghmatti_vehicle_data_simple.json)    <- this is a none bugged json : each object has its own label [WORKING non bugged test](https://i.imgur.com/nO1v4yL.png)
**WARNING THE LINKS ABOVE CONTAIN RAW GITHUB FILES THAT MAY LAG YOUR MACHINE DUE TO SHEER SIZE WITHIN VSC**
- Tested on Both Linux and Windows Machines with the same extensions installed.

**Comment by CriticalMax** [comment]
Well, seems like I should add a bit more info:
- Windows
- Same behaviour on VSCode and VSCode Insiders
- Used Test JSON 1 from @ioShinigami 
- Test JSON 2 works for me aswell
- No extensions installed which interfere with json

**Comment by schererja** [comment]
![image](https://user-images.githubusercontent.com/8645717/96186106-9211f880-0f00-11eb-852d-5e2b9472b63a.png)
Don't know if this is semi similar of an issue but looks like it might tie into all of it.

**Comment by cmgriffing** [comment]
Thanks again for this report. I am planning on deprecating JSON Biscuits since we now have it working within Assorted Biscuits which handles multiple languages now.
That extension also fixes this issue.

https://marketplace.visualstudio.com/items?itemName=CodeBiscuits.assorted-biscuits

Due to differences in how they are handled in the extensions, HTML, JS/TS, and CSS Biscuits will still be their own plugins.
